#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Windows" {
    search --fs-uuid --no-floppy --set=root C6C1-EF7D
    chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
